---
title: "Color Palettes in varutils"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{palettes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Many `varutils` give the change for the user to change the colors of the graph trough the argument `palette`. This argument can have multiple specifications:

- `NULL`, for the default ggplot colors
- A palette from a package, in the format `"pgk::palette_name"`
- A vector of colors, as defined in the [ggplot specs vignette](https://cran.r-project.org/web/packages/ggplot2/vignettes/ggplot2-specs.html):
  - A __name__, e.g., `"red"`. R has `r length(colours())` built-in named colours, which can be listed with `colours()`.
  - An __rgb specification__, with a string of the form `"#RRGGBB"` where each of the pairs `RR`, `GG`, `BB` consists of two hexadecimal digits giving a value in the range `00` to `FF`. You can optionally make the colour transparent by using the form `"#RRGGBBAA"`.
  - An __NA__, for a completely transparent colour.
  - The [munsell](https://github.com/cwickham/munsell) package, by Charlotte Wickham, makes it easy to choose specific colours using a system designed by Albert H. Munsell. If you invest a little in learning the system, it provides a convenient way of specifying aesthetically pleasing colours.
  
Suported packages and the possible `palette_name`'s are:

-------------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
base           rainbow, heat.colors, terrain.colors, topo.colors, cm.colors
viridis        viridis, magma, inferno, plasma, cividis, mako, rocket, turbo
RColorBrewer   Blues, BuGn, BuPu, GnBu, Greens, Greys, Oranges, OrRd, PuBu, PuBuGn, PuRd, Purples, RdPu, Reds, YlGn, YlGnBu, YlOrBr, YlOrRd, Accent, Dark2, Paired, Pastel1, Pastel2, Set1, Set2, Set3, BrBG, PiYG, PRGn, PuOr, RdBu, RdGy, RdYlBu, RdYlGn, Spectral     
ggsci          pal_npg, pal_aaas, pal_nejm, pal_lancet, pal_jama, pal_jco, pal_ucscgb, pal_d3, pal_locuszoom, pal_igv, pal_cosmic, pal_uchicago, pal_startrek, pal_tron, pal_futurama, pal_rickandmorty, pal_simpsons, pal_flatui, pal_frontiers, pal_gsea, pal_material 
-------------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
